#cloud-config

coreos:
  etcd2:
    proxy: on
    initial-cluster: etcdserver=http://10.6.0.4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
